version: "2"

services:
    backend:
        build: .
        ports:
            - 5000:5000
            - 9229:9229 #debugger port
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node-modules
        command: yarn run dev
        environment:
            - PORT=5000
